### ISSUE TITLE
Symfony 4 Console support

### ISSUE THREAD

**Issue by leroy0211** [eddiriarte/console-select#2]
The package does not work with Symfony 4 console. Due to the version constraints in composer.json

**Comment by eddiriarte** [comment]
Thx for that info... Ill check it later

**Comment by eddiriarte** [comment]
@leroy0211 due to conflicts with laravel 5.5 dependencies its not possible to update sf4 console without losing backward compatibility... 

However I'm preparing a release of a mayor version in order to support sf4. A pull request has been already opened, you could check if this fits your expectations, btw. ive uploaded a sample here: https://github.com/eddiriarte/console-select-sf4-sample 

Ill check if something else is broken or so, otherwise ill merge the changes in the next two days

**Comment by eddiriarte** [comment]
SF4 ist supported in version 2.0.0
